CREATE TABLE IF NOT EXISTS Leagues (
    `Name` VARCHAR(22) CHARACTER SET utf8,
    `Age` INT,
    `Club` VARCHAR(19) CHARACTER SET utf8,
    `Nationality` VARCHAR(11) CHARACTER SET utf8,
    `Position` VARCHAR(10) CHARACTER SET utf8,
    `League` VARCHAR(14) CHARACTER SET utf8,
    `Value_In_Million_Euros` NUMERIC(4, 1)
);
INSERT INTO Leagues VALUES
    ('Donnarumma',23,'Paris Saint Germain','Italy','Goalkeeper','Ligue 1',50),
    ('Marquinhos',28,'Paris Saint Germain','Brazil','Defender','Ligue 1',70),
    ('Presnel Kimpembe',27,'Paris Saint Germain','France','Defender','Ligue 1',40),
    ('Sergio Ramos',36,'Paris Saint Germain','Spain','Defender','Ligue 1',6),
    ('Hakimi',24,'Paris Saint Germain','Morocco','Defender','Ligue 1',12),
    ('Verratti',30,'Paris Saint Germain','Italy','Midfielder','Ligue 1',50),
    ('Vitinha',22,'Paris Saint Germain','Portugal','Midfielder','Ligue 1',45),
    ('Renato Sanches',25,'Paris Saint Germain','Portugal','Midfielder','Ligue 1',25),
    ('Neymar',30,'Paris Saint Germain','Brazil','Attacker','Ligue 1',75),
    ('Lionel Messi',35,'Paris Saint Germain','Argentina','Attacker','Ligue 1',50),
    ('Kylian Mbappe',23,'Paris Saint Germain','France','Attacker','Ligue 1',160),
    ('Danillo Pereira',31,'Paris Saint Germain','Portugal','Attacker','Ligue 1',12),
    ('Nuno Mendes',20,'Paris Saint Germain','Portugal','Defender','Ligue 1',60),
    ('Nubel',26,'AS Monaco','Germany','Goalkeeper','Ligue 1',10),
    ('Badiashile',21,'AS Monaco','France','Defender','Ligue 1',40),
    ('Disasi',24,'AS Monaco','France','Defender','Ligue 1',25),
    ('Malang Sarr',23,'AS Monaco','France','Defender','Ligue 1',8),
    ('Henrique',25,'AS Monaco','Brazil','Defender','Ligue 1',20),
    ('Fofana ',23,'AS Monaco','France','Midfielder','Ligue 1',25),
    ('Camara',22,'AS Monaco','Mali','Midfielder','Ligue 1',25),
    ('Golovin',26,'AS Monaco','Russia','Midfielder','Ligue 1',22),
    ('Minamino',27,'AS Monaco','Japan','Attacker','Ligue 1',10),
    ('Diata',23,'AS Monaco','Senegal','Attacker','Ligue 1',13),
    ('Martins',27,'AS Monaco','Portugal','Attacker','Ligue 1',10),
    ('Wissam Ben Yedder',32,'AS Monaco','France','Attacker','Ligue 1',20),
    ('Breel Embolo',25,'AS Monaco','Switzerland','Attacker','Ligue 1',20),
    ('Kevin Volland',30,'AS Monaco','Germany','Attacker','Ligue 1',16),
    ('Alemdar',20,'Stade Rennais FC','Turkey','Goalkeeper','Ligue 1',4),
    ('Theate',22,'Stade Rennais FC','Belgium','Defender','Ligue 1',30),
    ('Rodon',25,'Stade Rennais FC','Wales','Defender','Ligue 1',9),
    ('Omari',22,'Stade Rennais FC','France','Defender','Ligue 1',8),
    ('Truffert',21,'Stade Rennais FC','France','Defender','Ligue 1',15),
    ('Traore',30,'Stade Rennais FC','Mali','Defender','Ligue 1',10),
    ('Santamaria',27,'Stade Rennais FC','France','Midfielder','Ligue 1',16),
    ('Bourigeaud',28,'Stade Rennais FC','France','Midfielder','Ligue 1',18),
    ('Majer',24,'Stade Rennais FC','Croatia','Midfielder','Ligue 1',22),
    ('Doue',17,'Stade Rennais FC','France','Midfielder','Ligue 1',15),
    ('Terrier',25,'Stade Rennais FC','France','Attacker','Ligue 1',35),
    ('Sulemana',20,'Stade Rennais FC','Ghana','Attacker','Ligue 1',18),
    ('Doku',20,'Stade Rennais FC','Belgium','Attacker','Ligue 1',18),
    ('Kalimuendo',20,'Stade Rennais FC','France','Attacker','Ligue 1',25),
    ('Szczesny',32,'Juventus','Poland','Goalkeeper','Serie A',13),
    ('Bremer',25,'Juventus','Brazil','Defender','Serie A',40),
    ('Leonardo Bonucci ',35,'Juventus','Italy','Defender','Serie A',4),
    ('Alex Sandro',31,'Juventus','Brazil','Defender','Serie A',4.5),
    ('Danillo',31,'Juventus','Brazil','Defender','Serie A',12),
    ('Locatelli',24,'Juventus','Italy','Midfielder','Serie A',30),
    ('Leandro Paredes',28,'Juventus','Argentina','Midfielder','Serie A',15),
    ('Paul Pogba',29,'Juventus','France','Midfielder','Serie A',35),
    ('Weston McKennie',24,'Juventus','USA','Midfielder','Serie A',21),
    ('Adrien Rabiot',27,'Juventus','France','Midfielder','Serie A',18),
    ('Cuadrado',34,'Juventus','Columbia','Defender','Serie A',5),
    ('Filip Kostic',30,'Juventus','Serbia','Midfielder','Serie A',24),
    ('Federico Chiesa',25,'Juventus','Italy','Attacker','Serie A',60),
    ('Angel Di Maria',34,'Juventus','Argentina','Attacker','Serie A',10),
    ('Dusan Vlahovic',22,'Juventus','Serbia','Attacker','Serie A',80),
    ('Moise Kean',22,'Juventus','Italy','Attacker','Serie A',20),
    ('Milik',28,'Juventus','Poland','Attacker','Serie A',10),
    ('Meret',25,'Napoli','Italy','Goalkeeper','Serie A',12),
    ('Rrahmani',28,'Napoli','Albani','Defender','Serie A',25),
    ('Olivera',25,'Napoli','Uruguay','Defender','Serie A',15),
    ('Di Lorenzo',29,'Napoli','Italy','Defender','Serie A',25),
    ('Anguissa',27,'Napoli','Cameroon','Defender','Serie A',38),
    ('Ndombele',25,'Napoli','France','Midfielder','Serie A',28),
    ('Zielinski',28,'Napoli','Poland','Midfielder','Serie A',40),
    ('Kvaratskhelia',21,'Napoli','Georgia','Midfielder','Serie A',60),
    ('Lozano',27,'Napoli','Mexico','Attacker','Serie A',28),
    ('Politano',29,'Napoli','Italy','Attacker','Serie A',20),
    ('Raspadori',22,'Napoli','Italy','Attacker','Serie A',35),
    ('Osimhen',23,'Napoli','Nigeria','Attacker','Serie A',70),
    ('Simeone',27,'Napoli','Argentina','Attacker','Serie A',17),
    ('Onana',26,'Inter Milan','Cameroon','Goalkeeper','Serie A',14),
    ('Skriniar',27,'Inter Milan','Slovakia','Defender','Serie A',60),
    ('Bastoni',23,'Inter Milan','Italy','Defender','Serie A',55),
    ('Stefan de Vrij',30,'Inter Milan','Netherland','Defender','Serie A',15),
    ('Ambrosio',34,'Inter Milan','Italy','Defender','Serie A',2),
    ('Brozovic',30,'Inter Milan','Croatia','Defender','Serie A',35),
    ('Barella',25,'Inter Milan','Italy','Midfielder','Serie A',70),
    ('Calhanoglu',28,'Inter Milan','Turkey','Midfielder','Serie A',35),
    ('Dumfries',26,'Inter Milan','Netherland','Midfielder','Serie A',28),
    ('Gosens',28,'Inter Milan','Germany','Defender','Serie A',18),
    ('Lautaro Martinez',25,'Inter Milan','Argentina','Attacker','Serie A',75),
    ('Romelu Lukaku',29,'Inter Milan','Belgium','Attacker','Serie A',55),
    ('Edin Dzeko',36,'Inter Milan','Bosnia','Attacker','Serie A',4),
    ('Mkhitaryan',33,'Inter Milan','Armenia','Attacker','Serie A',6),
    ('Ederson',29,'Mancester City','Brazil','Goalkeeper','Premier League',45),
    ('Ruben Dias',25,'Mancester City','Portugal','Defender','Premier League',75),
    ('Aymeric Laporte',28,'Mancester City','Spain','Defender','Premier League',38),
    ('John Stones',28,'Mancester City','England','Defender','Premier League',30),
    ('Manuel Akanji',27,'Mancester City','Switzerland','Defender','Premier League',30),
    ('Joao Cancelo',28,'Mancester City','Portugal','Defender','Premier League',70),
    ('Kyle Walker',32,'Mancester City','England','Defender','Premier League',15),
    ('Rodri',26,'Mancester City','Spain','Midfielder','Premier League',80),
    ('Phil Foden',22,'Mancester City','England','Midfielder','Premier League',110),
    ('Kevin De Bruyne',31,'Mancester City','Belgium','Midfielder','Premier League',80),
    ('Ilkay Gundogan',32,'Mancester City','Germany','Midfielder','Premier League',25),
    ('Bernardo Silva',28,'Mancester City','Portugal','Midfielder','Premier League',80),
    ('Jack Grealish',27,'Mancester City','England','Attacker','Premier League',70),
    ('Riyad Mahrez',31,'Mancester City','Algeria','Attacker','Premier League',30),
    ('Erling Haaland',22,'Mancester City','Norway','Attacker','Premier League',170),
    ('Alisson',30,'Liverpool','Brazil','Goalkeeper','Premier League',50),
    ('Virgil van Dijk',31,'Liverpool','Netherland','Defender','Premier League',50),
    ('Ibrahim Konate',23,'Liverpool','France','Defender','Premier League',35),
    ('Joel Matip',31,'Liverpool','Cameroon','Defender','Premier League',16),
    ('Robertson',28,'Liverpool','Scotland','Defender','Premier League',55),
    ('Trent Alexander Arnold',24,'Liverpool','England','Defender','Premier League',70),
    ('Fabinho',29,'Liverpool','Brazil','Midfielder','Premier League',55),
    ('Thiago',31,'Liverpool','Spain','Midfielder','Premier League',18),
    ('Jordan Henderson',32,'Liverpool','England','Midfielder','Premier League',15),
    ('Diogo Jota',26,'Liverpool','Portugal','Attacker','Premier League',55),
    ('Luiz Diaz',25,'Liverpool','Columbia','Attacker','Premier League',75),
    ('Mohamed Salah',30,'Liverpool','Egypt','Attacker','Premier League',80),
    ('Darwin Nunez',23,'Liverpool','Uruguay','Attacker','Premier League',70),
    ('Roberto Firmino',31,'Liverpool','Brazil','Attacker','Premier League',28),
    ('David De Gea',32,'Mancester United','Spain','Goalkeeper','Premier League',15),
    ('Lisandro Martinez',24,'Mancester United','Argentina','Defender','Premier League',50),
    ('Raphael Varane',29,'Mancester United','France','Defender','Premier League',40),
    ('Harry Maguire',29,'Mancester United','England','Defender','Premier League',30),
    ('Luke Shaw',27,'Mancester United','England','Defender','Premier League',28),
    ('Malacia',23,'Mancester United','Netherland','Defender','Premier League',22),
    ('Casemiro',30,'Mancester United','Brazil','Midfielder','Premier League',50),
    ('McTominay',25,'Mancester United','Scotland','Midfielder','Premier League',30),
    ('Fred',29,'Mancester United','Brazil','Midfielder','Premier League',20),
    ('Bruno Fernandes',28,'Mancester United','Portugal','Midfielder','Premier League',75),
    ('Eriksen',30,'Mancester United','Denmark','Attacker','Premier League',25),
    ('Jadon Sancho',22,'Mancester United','England','Attacker','Premier League',60),
    ('Marcus Rashford',25,'Mancester United','England','Attacker','Premier League',55),
    ('Antony',22,'Mancester United','Brazil','Attacker','Premier League',75),
    ('Martial',26,'Mancester United','France','Attacker','Premier League',15),
    ('Thibaut Coutois',30,'Real Madrid','Belgium','Goalkeeper','La Liga',60),
    ('Militao',24,'Real Madrid','Brazil','Defender','La Liga',60),
    ('David Alaba',30,'Real Madrid','Austria','Defender','La Liga',55),
    ('Rudiger',29,'Real Madrid','Germany','Defender','La Liga',40),
    ('Dani Carvajal',30,'Real Madrid','Spain','Defender','La Liga',18),
    ('Tchouameni',22,'Real Madrid','France','Midfielder','La Liga',80),
    ('Fede Valverde',24,'Real Madrid','Uruguay','Midfielder','La Liga',100),
    ('Toni Kroos',32,'Real Madrid','Germany','Midfielder','La Liga',20),
    ('Luka Modric',37,'Real Madrid','Croatia','Midfielder','La Liga',10),
    ('Vinicius Junior',22,'Real Madrid','Brazil','Attacker','La Liga',120),
    ('Eden Hazard',31,'Real Madrid','Belgium','Attacker','La Liga',7.5),
    ('Rodrygo',21,'Real Madrid','Brazil','Attacker','La Liga',80),
    ('Marco Asensio',26,'Real Madrid','Spain','Attacker','La Liga',25),
    ('Karim Benzema',34,'Real Madrid','France','Attacker','La Liga',35),
    ('Camavinga',20,'Real Madrid','France','Midfielder','La Liga',50),
    ('ter Stegen',30,'Barcelona','Germany','Goalkeeper','La Liga',30),
    ('Ronald Araujo',23,'Barcelona','Uruguay','Defender','La Liga',60),
    ('Jules Kounde',24,'Barcelona','France','Defender','La Liga',60),
    ('Christensen',26,'Barcelona','Denmark','Defender','La Liga',30),
    ('Marcos Alonso',31,'Barcelona','Spain','Defender','La Liga',9),
    ('Jordi Alba',33,'Barcelona','Spain','Defender','La Liga',5),
    ('Sergio Busquets',34,'Barcelona','Spain','Midfielder','La Liga',5),
    ('Pedri',20,'Barcelona','Spain','Midfielder','La Liga',100),
    ('Gavi',18,'Barcelona','Spain','Midfielder','La Liga',90),
    ('Frenkie de Jong',25,'Barcelona','Netherland','Midfielder','La Liga',50),
    ('Ansu Fati',20,'Barcelona','Spain','Attacker','La Liga',50),
    ('Ferran Torres',22,'Barcelona','Spain','Attacker','La Liga',35),
    ('Ousmane Dembele',25,'Barcelona','France','Attacker','La Liga',60),
    ('Raphinha ',25,'Barcelona','Brazil','Attacker','La Liga',50),
    ('Robert Lewandowski',34,'Barcelona','Poland','Attacker','La Liga',45),
    ('Jan Oblak',29,'Atletico Madrid','Slovakia','Goalkeeper','La Liga',40),
    ('Gimenez',27,'Atletico Madrid','Uruguay','Defender','La Liga',40),
    ('Hermoso',27,'Atletico Madrid','Spain','Defender','La Liga',14),
    ('Felipe',33,'Atletico Madrid','Brazil','Defender','La Liga',3),
    ('Reguilon',25,'Atletico Madrid','Spain','Defender','La Liga',20),
    ('Kondogbia',29,'Atletico Madrid','France','Defender','La Liga',20),
    ('Axel Witsel',33,'Atletico Madrid','Belgium','Midfielder','La Liga',5),
    ('de Paul',28,'Atletico Madrid','Argentina','Midfielder','La Liga',35),
    ('Llorente',27,'Atletico Madrid','Spain','Midfielder','La Liga',35),
    ('Koke',30,'Atletico Madrid','Spain','Midfielder','La Liga',18),
    ('Saul Niguez',28,'Atletico Madrid','Spain','Midfielder','La Liga',15),
    ('Thomas Lemar',27,'Atletico Madrid','France','Midfielder','La Liga',30),
    ('Carrasco',29,'Atletico Madrid','Belgium','Midfielder','La Liga',30),
    ('Correa',27,'Atletico Madrid','Argentina','Attacker','La Liga',40),
    ('Joao Felix',23,'Atletico Madrid','Portugal','Attacker','La Liga',50),
    ('Antoine Griezmann',31,'Atletico Madrid','France','Attacker','La Liga',31),
    ('Morata',30,'Atletico Madrid','Spain','Attacker','La Liga',25),
    ('Manuel Neuer',36,'Bayern Munich','Germany','Goalkeeper','Bundesliga',12),
    ('Matthijs de Ligt',23,'Bayern Munich','Netherland','Defender','Bundesliga',70),
    ('Dayot Upamecano',24,'Bayern Munich','France','Defender','Bundesliga',50),
    ('Lucas Hernandez',26,'Bayern Munich','France','Defender','Bundesliga',50),
    ('Alphonso Davies',22,'Bayern Munich','Canada','Defender','Bundesliga',70),
    ('Benjamin Pavard',26,'Bayern Munich','France','Defender','Bundesliga',35),
    ('Joshua Kimmich',27,'Bayern Munich','Germany','Midfielder','Bundesliga',80),
    ('Leon Goretzka',27,'Bayern Munich','Germany','Midfielder','Bundesliga',65),
    ('Leroy Sane',26,'Bayern Munich','Germany','Attacker','Bundesliga',70),
    ('Sadio Mane',30,'Bayern Munich','Senegal','Attacker','Bundesliga',60),
    ('Serge Gnabry',27,'Bayern Munich','Germany','Attacker','Bundesliga',65),
    ('Thomas Muller',33,'Bayern Munich','Germany','Attacker','Bundesliga',18),
    ('Gregor Kobel',24,'Borussia Dortmund','Switzerland','Goalkeeper','Bundesliga',25),
    ('Niklas Sule',27,'Borussia Dortmund','Germany','Defender','Bundesliga',35),
    ('Nico Schotterbeck',23,'Borussia Dortmund','Germany','Defender','Bundesliga',33),
    ('Mats Hummels',33,'Borussia Dortmund','Germany','Defender','Bundesliga',6.5),
    ('Raphael Guerreiro',28,'Borussia Dortmund','Portugal','Defender','Bundesliga',20),
    ('Nico Schulz',29,'Borussia Dortmund','Germany','Midfielder','Bundesliga',2),
    ('Marius Wolf',27,'Borussia Dortmund','Germany','Midfielder','Bundesliga',6.5),
    ('Thomas Meunier',31,'Borussia Dortmund','Belgium','Midfielder','Bundesliga',6.5),
    ('Emre Can',28,'Borussia Dortmund','Germany','Midfielder','Bundesliga',14),
    ('Jude Bellingham',19,'Borussia Dortmund','England','Midfielder','Bundesliga',100),
    ('Mahmoud Dahoud',26,'Borussia Dortmund','Germany','Midfielder','Bundesliga',18),
    ('Giovanni Reyna',20,'Borussia Dortmund','USA','Attacker','Bundesliga',35),
    ('Julian Brandt',26,'Borussia Dortmund','Germany','Attacker','Bundesliga',28),
    ('Marco Reus',33,'Borussia Dortmund','Germany','Attacker','Bundesliga',9),
    ('Donyell Malen',23,'Borussia Dortmund','Netherland','Attacker','Bundesliga',9),
    ('Thorgan Hazard',29,'Borussia Dortmund','Belgium','Attacker','Bundesliga',9),
    ('Karim Adeyemi',20,'Borussia Dortmund','Germany','Attacker','Bundesliga',35),
    ('Anthony Modeste',34,'Borussia Dortmund','France','Attacker','Bundesliga',4),
    ('Peter Gulacsi',32,'RB Leipzig','Hungary','Goalkeeper','Bundesliga',6),
    ('Josko Gvardiol',20,'RB Leipzig','Croatia','Defender','Bundesliga',60),
    ('Mohamed Simakan',22,'RB Leipzig','France','Defender','Bundesliga',28),
    ('Abdou Diallo',26,'RB Leipzig','Senegal','Defender','Bundesliga',15),
    ('Willi Orban',30,'RB Leipzig','Hungary','Defender','Bundesliga',10),
    ('David Raum',24,'RB Leipzig','Germany','Defender','Bundesliga',26),
    ('Marcel Halstenberg',31,'RB Leipzig','Germany','Defender','Bundesliga',4),
    ('Benjamin Henrichs',25,'RB Leipzig','Germany','Defender','Bundesliga',15),
    ('Lukas Klostermann',26,'RB Leipzig','Germany','Defender','Bundesliga',14),
    ('Konrad Laimer',25,'RB Leipzig','Austria','Midfielder','Bundesliga',28),
    ('Dani Olmo',24,'RB Leipzig','Spain','Midfielder','Bundesliga',40),
    ('Dominik Szoboszlai',22,'RB Leipzig','Hungary','Midfielder','Bundesliga',35),
    ('Emil Forsberg',31,'RB Leipzig','Sweden','Midfielder','Bundesliga',9),
    ('Christopher Nkunku',25,'RB Leipzig','France','Attacker','Bundesliga',80),
    ('Timo Werner',26,'RB Leipzig','Germany','Attacker','Bundesliga',25),
    ('Andre Silva',27,'RB Leipzig','Portugal','Attacker','Bundesliga',24),
    ('Yussuf Poulsen',28,'RB Leipzig','Denmark','Attacker','Bundesliga',10);
